feat: auth repository
somnio-software/flutter-firebase-starter pull request #128
Opened 2021-07-28 16:53 UTC by hchaviano

2021-07-29 21:56 UTC, gonzasosa requested changes

2021-07-29 21:56 UTC, gonzasosa commented on packages/auth/lib/src/auth_service.dart
> +      {@required SocialMediaMethod method});
```suggestion
      {@required SocialMediaMethod method,});
```

2021-07-29 21:56 UTC, gonzasosa commented on packages/auth/lib/src/firebase_init_service.dart
> +        signInServiceFactory: _serviceFactory);
```suggestion
        signInServiceFactory: _serviceFactory,);
```

2021-07-29 21:56 UTC, gonzasosa commented on packages/auth/lib/src/firebase_init_service.dart
> +            method: element, constructor: () => _services[element]);
```suggestion
            method: element, constructor: () => _services[element],);
```

2021-07-29 21:56 UTC, gonzasosa commented on packages/auth/lib/src/firebase_init_service.dart
> +        AppleSignInService(appleCredentials: const AppleCredentials()),
```suggestion
        AppleSignInService(appleCredentials: const AppleCredentials(),),
```

2021-07-29 21:56 UTC, gonzasosa commented on test/services/auth/sign_in_services/google_sign_in_service_test.dart
> +import 'package:firebase_auth/firebase_auth.dart' as auth;
```suggestion
import 'package:firebase_auth/firebase_auth.dart' as Auth;
```

2021-07-29 21:56 UTC, gonzasosa commented on lib/edit_profile/bloc/edit_profile_bloc.dart
> +        return _toUser(await _authService.currentUser());
```suggestion
        final user = await _authService.currentUser();
        return _toUser(user);
```

2021-07-29 21:56 UTC, gonzasosa commented on lib/models/user.dart
> +  // final String address;
Remove this comments

2021-07-29 21:56 UTC, gonzasosa commented on lib/models/user.dart
> +    // this.address,
Please also remove this comments

2021-07-29 21:56 UTC, gonzasosa commented on lib/models/user.dart
> +        // address: json['address'],
Same here about the comments

2021-07-29 21:56 UTC, gonzasosa commented on lib/models/user.dart
> +        // 'phoneNumber': phoneNumber,
Same on comments

2021-07-29 21:56 UTC, gonzasosa commented on lib/models/user.dart
> +        // address: entity.address,
Same on comments

2021-07-29 21:56 UTC, gonzasosa commented on lib/models/user.dart
> +        // address
Also remove this one 😅

2021-07-30 12:20 UTC, hchaviano commented on test/services/auth/sign_in_services/google_sign_in_service_test.dart
> +import 'package:firebase_auth/firebase_auth.dart' as auth;
The new linter recommends using lowerCamelCase for this case

2021-07-30 14:22 UTC, gonzasosa approved these changes

2021-07-30 14:22 UTC, merged